// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: barang.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBarang = `-- name: CreateBarang :one
INSERT INTO barang (nama, harga, stok, image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, nama, harga, stok, is_active, image_url, created_at, updated_at
`

type CreateBarangParams struct {
	Nama     string         `json:"nama"`
	Harga    pgtype.Numeric `json:"harga"`
	Stok     int32          `json:"stok"`
	ImageUrl string         `json:"image_url"`
}

func (q *Queries) CreateBarang(ctx context.Context, arg CreateBarangParams) (Barang, error) {
	row := q.db.QueryRow(ctx, createBarang,
		arg.Nama,
		arg.Harga,
		arg.Stok,
		arg.ImageUrl,
	)
	var i Barang
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Harga,
		&i.Stok,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBarang = `-- name: DeleteBarang :one
DELETE FROM barang
WHERE id = $1
RETURNING id, nama, harga, stok, is_active, image_url, created_at, updated_at
`

func (q *Queries) DeleteBarang(ctx context.Context, id pgtype.UUID) (Barang, error) {
	row := q.db.QueryRow(ctx, deleteBarang, id)
	var i Barang
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Harga,
		&i.Stok,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBarangAsc = `-- name: ListBarangAsc :many
SELECT
  id,
  nama,
  harga,
  stok,
  image_url,
  is_active
FROM barang
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListBarangAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListBarangAscRow struct {
	ID       pgtype.UUID    `json:"id"`
	Nama     string         `json:"nama"`
	Harga    pgtype.Numeric `json:"harga"`
	Stok     int32          `json:"stok"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) ListBarangAsc(ctx context.Context, arg ListBarangAscParams) ([]ListBarangAscRow, error) {
	rows, err := q.db.Query(ctx, listBarangAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBarangAscRow
	for rows.Next() {
		var i ListBarangAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Harga,
			&i.Stok,
			&i.ImageUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBarangDesc = `-- name: ListBarangDesc :many
SELECT
  id,
  nama,
  harga,
  stok,
  image_url,
  is_active
FROM barang
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBarangDescParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListBarangDescRow struct {
	ID       pgtype.UUID    `json:"id"`
	Nama     string         `json:"nama"`
	Harga    pgtype.Numeric `json:"harga"`
	Stok     int32          `json:"stok"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) ListBarangDesc(ctx context.Context, arg ListBarangDescParams) ([]ListBarangDescRow, error) {
	rows, err := q.db.Query(ctx, listBarangDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBarangDescRow
	for rows.Next() {
		var i ListBarangDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Harga,
			&i.Stok,
			&i.ImageUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBarang = `-- name: UpdateBarang :one
UPDATE barang SET
  nama = $2,
  harga = $3,
  stok = $4,
  image_url = $5,
  updated_at = NOW()
WHERE id = $1
RETURNING id, nama, harga, stok, is_active, image_url, created_at, updated_at
`

type UpdateBarangParams struct {
	ID       pgtype.UUID    `json:"id"`
	Nama     string         `json:"nama"`
	Harga    pgtype.Numeric `json:"harga"`
	Stok     int32          `json:"stok"`
	ImageUrl string         `json:"image_url"`
}

func (q *Queries) UpdateBarang(ctx context.Context, arg UpdateBarangParams) (Barang, error) {
	row := q.db.QueryRow(ctx, updateBarang,
		arg.ID,
		arg.Nama,
		arg.Harga,
		arg.Stok,
		arg.ImageUrl,
	)
	var i Barang
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Harga,
		&i.Stok,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
