// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, phone, address)
VALUES ($1, $2, $3)
RETURNING id, name, phone, address, created_at
`

type CreateCustomerParams struct {
	Name    string      `json:"name"`
	Phone   pgtype.Text `json:"phone"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.Phone, arg.Address)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :one
DELETE FROM customers
WHERE id = $1
RETURNING id, name, phone, address, created_at
`

func (q *Queries) DeleteCustomer(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, deleteCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT
  id,
  name,
  phone,
  address,
  created_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomerAsc = `-- name: ListCustomerAsc :many
SELECT
  id,
  name,
  phone,
  address,
  created_at
FROM customers
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListCustomerAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomerAsc(ctx context.Context, arg ListCustomerAscParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomerAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerDesc = `-- name: ListCustomerDesc :many
SELECT
  id,
  name,
  phone,
  address,
  created_at
FROM customers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomerDescParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomerDesc(ctx context.Context, arg ListCustomerDescParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomerDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers SET
  name = $2,
  phone = $3,
  address = $4
WHERE id = $1
RETURNING id, name, phone, address, created_at
`

type UpdateCustomerParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Phone   pgtype.Text `json:"phone"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Address,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
