// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: detail_transactions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDetailTransaction = `-- name: CreateDetailTransaction :one
INSERT INTO detail_transactions (
  id_transaction,
  id_product,
  qty,
  price,
  subtotal
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, id_transaction, id_product, qty, price, subtotal
`

type CreateDetailTransactionParams struct {
	IDTransaction pgtype.UUID    `json:"id_transaction"`
	IDProduct     pgtype.UUID    `json:"id_product"`
	Qty           int32          `json:"qty"`
	Price         pgtype.Numeric `json:"price"`
	Subtotal      pgtype.Numeric `json:"subtotal"`
}

func (q *Queries) CreateDetailTransaction(ctx context.Context, arg CreateDetailTransactionParams) (DetailTransaction, error) {
	row := q.db.QueryRow(ctx, createDetailTransaction,
		arg.IDTransaction,
		arg.IDProduct,
		arg.Qty,
		arg.Price,
		arg.Subtotal,
	)
	var i DetailTransaction
	err := row.Scan(
		&i.ID,
		&i.IDTransaction,
		&i.IDProduct,
		&i.Qty,
		&i.Price,
		&i.Subtotal,
	)
	return i, err
}

const getDetailTransaction = `-- name: GetDetailTransaction :many
SELECT
  d.id,
  d.id_transaction,
  d.id_product,
  d.qty,
  d.price,
  d.subtotal,
  p.name as product_name
FROM detail_transactions d
JOIN products p ON d.id_product = p.id
WHERE d.id_transaction = $1
`

type GetDetailTransactionRow struct {
	ID            pgtype.UUID    `json:"id"`
	IDTransaction pgtype.UUID    `json:"id_transaction"`
	IDProduct     pgtype.UUID    `json:"id_product"`
	Qty           int32          `json:"qty"`
	Price         pgtype.Numeric `json:"price"`
	Subtotal      pgtype.Numeric `json:"subtotal"`
	ProductName   string         `json:"product_name"`
}

func (q *Queries) GetDetailTransaction(ctx context.Context, idTransaction pgtype.UUID) ([]GetDetailTransactionRow, error) {
	rows, err := q.db.Query(ctx, getDetailTransaction, idTransaction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetailTransactionRow
	for rows.Next() {
		var i GetDetailTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.IDTransaction,
			&i.IDProduct,
			&i.Qty,
			&i.Price,
			&i.Subtotal,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
