// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: detail_penjualan.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDetailPenjualan = `-- name: CreateDetailPenjualan :one
INSERT INTO detail_penjualan (
  id_penjualan,
  id_barang,
  jumlah,
  harga_saat_transaksi,
  subtotal
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateDetailPenjualanParams struct {
	IDPenjualan        pgtype.UUID    `json:"id_penjualan"`
	IDBarang           pgtype.UUID    `json:"id_barang"`
	Jumlah             int32          `json:"jumlah"`
	HargaSaatTransaksi pgtype.Numeric `json:"harga_saat_transaksi"`
	Subtotal           pgtype.Numeric `json:"subtotal"`
}

func (q *Queries) CreateDetailPenjualan(ctx context.Context, arg CreateDetailPenjualanParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDetailPenjualan,
		arg.IDPenjualan,
		arg.IDBarang,
		arg.Jumlah,
		arg.HargaSaatTransaksi,
		arg.Subtotal,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getDetailPenjualan = `-- name: GetDetailPenjualan :many
SELECT
  d.id,
  d.id_penjualan,
  d.id_barang,
  d.jumlah,
  d.harga_saat_transaksi,
  d.subtotal,
  b.nama as nama_barang
FROM detail_penjualan d
JOIN barang b ON d.id_barang = b.id
WHERE d.id_penjualan = $1
`

type GetDetailPenjualanRow struct {
	ID                 pgtype.UUID    `json:"id"`
	IDPenjualan        pgtype.UUID    `json:"id_penjualan"`
	IDBarang           pgtype.UUID    `json:"id_barang"`
	Jumlah             int32          `json:"jumlah"`
	HargaSaatTransaksi pgtype.Numeric `json:"harga_saat_transaksi"`
	Subtotal           pgtype.Numeric `json:"subtotal"`
	NamaBarang         string         `json:"nama_barang"`
}

func (q *Queries) GetDetailPenjualan(ctx context.Context, idPenjualan pgtype.UUID) ([]GetDetailPenjualanRow, error) {
	rows, err := q.db.Query(ctx, getDetailPenjualan, idPenjualan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetailPenjualanRow
	for rows.Next() {
		var i GetDetailPenjualanRow
		if err := rows.Scan(
			&i.ID,
			&i.IDPenjualan,
			&i.IDBarang,
			&i.Jumlah,
			&i.HargaSaatTransaksi,
			&i.Subtotal,
			&i.NamaBarang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
