// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PembayaranMetode string

const (
	PembayaranMetodeCash   PembayaranMetode = "cash"
	PembayaranMetodeQris   PembayaranMetode = "qris"
	PembayaranMetodeDebit  PembayaranMetode = "debit"
	PembayaranMetodeKredit PembayaranMetode = "kredit"
)

func (e *PembayaranMetode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PembayaranMetode(s)
	case string:
		*e = PembayaranMetode(s)
	default:
		return fmt.Errorf("unsupported scan type for PembayaranMetode: %T", src)
	}
	return nil
}

type NullPembayaranMetode struct {
	PembayaranMetode PembayaranMetode `json:"pembayaran_metode"`
	Valid            bool             `json:"valid"` // Valid is true if PembayaranMetode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPembayaranMetode) Scan(value interface{}) error {
	if value == nil {
		ns.PembayaranMetode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PembayaranMetode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPembayaranMetode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PembayaranMetode), nil
}

type PembayaranStatus string

const (
	PembayaranStatusPending PembayaranStatus = "pending"
	PembayaranStatusLunas   PembayaranStatus = "lunas"
	PembayaranStatusGagal   PembayaranStatus = "gagal"
)

func (e *PembayaranStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PembayaranStatus(s)
	case string:
		*e = PembayaranStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PembayaranStatus: %T", src)
	}
	return nil
}

type NullPembayaranStatus struct {
	PembayaranStatus PembayaranStatus `json:"pembayaran_status"`
	Valid            bool             `json:"valid"` // Valid is true if PembayaranStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPembayaranStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PembayaranStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PembayaranStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPembayaranStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PembayaranStatus), nil
}

type Roles string

const (
	RolesAdmin Roles = "admin"
	RolesUser  Roles = "user"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type NullRoles struct {
	Roles Roles `json:"roles"`
	Valid bool  `json:"valid"` // Valid is true if Roles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoles) Scan(value interface{}) error {
	if value == nil {
		ns.Roles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roles), nil
}

type Barang struct {
	ID        pgtype.UUID        `json:"id"`
	Nama      string             `json:"nama"`
	Harga     pgtype.Numeric     `json:"harga"`
	Stok      int32              `json:"stok"`
	IsActive  bool               `json:"is_active"`
	ImageUrl  string             `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DetailPenjualan struct {
	ID                 pgtype.UUID    `json:"id"`
	IDPenjualan        pgtype.UUID    `json:"id_penjualan"`
	IDBarang           pgtype.UUID    `json:"id_barang"`
	Jumlah             int32          `json:"jumlah"`
	HargaSaatTransaksi pgtype.Numeric `json:"harga_saat_transaksi"`
	Subtotal           pgtype.Numeric `json:"subtotal"`
}

type Pelanggan struct {
	ID        pgtype.UUID        `json:"id"`
	Nama      string             `json:"nama"`
	NoHp      pgtype.Text        `json:"no_hp"`
	Alamat    pgtype.Text        `json:"alamat"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Penjualan struct {
	ID                 pgtype.UUID        `json:"id"`
	IDUser             pgtype.UUID        `json:"id_user"`
	IDPelanggan        pgtype.UUID        `json:"id_pelanggan"`
	Tanggal            pgtype.Timestamptz `json:"tanggal"`
	Total              pgtype.Numeric     `json:"total"`
	MetodePembayaran   PembayaranMetode   `json:"metode_pembayaran"`
	StatusPembayaran   PembayaranStatus   `json:"status_pembayaran"`
	IDTransaksiGateway pgtype.Text        `json:"id_transaksi_gateway"`
}

type User struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Password string      `json:"password"`
	Role     Roles       `json:"role"`
	ImageUrl string      `json:"image_url"`
	IsActive pgtype.Bool `json:"is_active"`
}
