// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pelanggan.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPelanggan = `-- name: CreatePelanggan :one
INSERT INTO pelanggan (nama, no_hp, alamat)
VALUES ($1, $2, $3)
RETURNING id, nama, no_hp, alamat, created_at
`

type CreatePelangganParams struct {
	Nama   string      `json:"nama"`
	NoHp   pgtype.Text `json:"no_hp"`
	Alamat pgtype.Text `json:"alamat"`
}

func (q *Queries) CreatePelanggan(ctx context.Context, arg CreatePelangganParams) (Pelanggan, error) {
	row := q.db.QueryRow(ctx, createPelanggan, arg.Nama, arg.NoHp, arg.Alamat)
	var i Pelanggan
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.NoHp,
		&i.Alamat,
		&i.CreatedAt,
	)
	return i, err
}

const deletePelanggan = `-- name: DeletePelanggan :one
DELETE FROM pelanggan
WHERE id = $1
RETURNING id, nama, no_hp, alamat, created_at
`

func (q *Queries) DeletePelanggan(ctx context.Context, id pgtype.UUID) (Pelanggan, error) {
	row := q.db.QueryRow(ctx, deletePelanggan, id)
	var i Pelanggan
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.NoHp,
		&i.Alamat,
		&i.CreatedAt,
	)
	return i, err
}

const getPelangganByID = `-- name: GetPelangganByID :one
SELECT
  id,
  nama,
  no_hp,
  alamat,
  created_at
FROM pelanggan
WHERE id = $1
`

func (q *Queries) GetPelangganByID(ctx context.Context, id pgtype.UUID) (Pelanggan, error) {
	row := q.db.QueryRow(ctx, getPelangganByID, id)
	var i Pelanggan
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.NoHp,
		&i.Alamat,
		&i.CreatedAt,
	)
	return i, err
}

const listPelangganAsc = `-- name: ListPelangganAsc :many
SELECT
  id,
  nama,
  no_hp,
  alamat,
  created_at
FROM pelanggan
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListPelangganAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPelangganAsc(ctx context.Context, arg ListPelangganAscParams) ([]Pelanggan, error) {
	rows, err := q.db.Query(ctx, listPelangganAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pelanggan
	for rows.Next() {
		var i Pelanggan
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.NoHp,
			&i.Alamat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPelangganDesc = `-- name: ListPelangganDesc :many
SELECT
  id,
  nama,
  no_hp,
  alamat,
  created_at
FROM pelanggan
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPelangganDescParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPelangganDesc(ctx context.Context, arg ListPelangganDescParams) ([]Pelanggan, error) {
	rows, err := q.db.Query(ctx, listPelangganDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pelanggan
	for rows.Next() {
		var i Pelanggan
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.NoHp,
			&i.Alamat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePelanggan = `-- name: UpdatePelanggan :one
UPDATE pelanggan SET
  nama = $2,
  no_hp = $3,
  alamat = $4
WHERE id = $1
RETURNING id, nama, no_hp, alamat, created_at
`

type UpdatePelangganParams struct {
	ID     pgtype.UUID `json:"id"`
	Nama   string      `json:"nama"`
	NoHp   pgtype.Text `json:"no_hp"`
	Alamat pgtype.Text `json:"alamat"`
}

func (q *Queries) UpdatePelanggan(ctx context.Context, arg UpdatePelangganParams) (Pelanggan, error) {
	row := q.db.QueryRow(ctx, updatePelanggan,
		arg.ID,
		arg.Nama,
		arg.NoHp,
		arg.Alamat,
	)
	var i Pelanggan
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.NoHp,
		&i.Alamat,
		&i.CreatedAt,
	)
	return i, err
}
