// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: penjualan.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPenjualan = `-- name: CreatePenjualan :one
INSERT INTO penjualan (
  id_user,
  id_pelanggan,
  total,
  metode_pembayaran,
  status_pembayaran,
  id_transaksi_gateway
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, id_user, id_pelanggan, tanggal, total, metode_pembayaran, status_pembayaran, id_transaksi_gateway
`

type CreatePenjualanParams struct {
	IDUser             pgtype.UUID      `json:"id_user"`
	IDPelanggan        pgtype.UUID      `json:"id_pelanggan"`
	Total              pgtype.Numeric   `json:"total"`
	MetodePembayaran   PembayaranMetode `json:"metode_pembayaran"`
	StatusPembayaran   PembayaranStatus `json:"status_pembayaran"`
	IDTransaksiGateway pgtype.Text      `json:"id_transaksi_gateway"`
}

func (q *Queries) CreatePenjualan(ctx context.Context, arg CreatePenjualanParams) (Penjualan, error) {
	row := q.db.QueryRow(ctx, createPenjualan,
		arg.IDUser,
		arg.IDPelanggan,
		arg.Total,
		arg.MetodePembayaran,
		arg.StatusPembayaran,
		arg.IDTransaksiGateway,
	)
	var i Penjualan
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDPelanggan,
		&i.Tanggal,
		&i.Total,
		&i.MetodePembayaran,
		&i.StatusPembayaran,
		&i.IDTransaksiGateway,
	)
	return i, err
}

const listPenjualan = `-- name: ListPenjualan :many
SELECT
  p.id,
  p.id_user,
  p.id_pelanggan,
  p.total,
  p.tanggal,
  p.metode_pembayaran,
  p.status_pembayaran,
  p.id_transaksi_gateway,
  pl.nama AS nama_pelanggan,
  u.username AS kasir
FROM penjualan p
LEFT JOIN pelanggan pl ON p.id_pelanggan = pl.id
JOIN users u ON p.id_user = u.id
WHERE tanggal BETWEEN $1 AND $2
ORDER BY p.tanggal DESC
LIMIT $3 OFFSET $4
`

type ListPenjualanParams struct {
	Tanggal   pgtype.Timestamptz `json:"tanggal"`
	Tanggal_2 pgtype.Timestamptz `json:"tanggal_2"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
}

type ListPenjualanRow struct {
	ID                 pgtype.UUID        `json:"id"`
	IDUser             pgtype.UUID        `json:"id_user"`
	IDPelanggan        pgtype.UUID        `json:"id_pelanggan"`
	Total              pgtype.Numeric     `json:"total"`
	Tanggal            pgtype.Timestamptz `json:"tanggal"`
	MetodePembayaran   PembayaranMetode   `json:"metode_pembayaran"`
	StatusPembayaran   PembayaranStatus   `json:"status_pembayaran"`
	IDTransaksiGateway pgtype.Text        `json:"id_transaksi_gateway"`
	NamaPelanggan      pgtype.Text        `json:"nama_pelanggan"`
	Kasir              string             `json:"kasir"`
}

func (q *Queries) ListPenjualan(ctx context.Context, arg ListPenjualanParams) ([]ListPenjualanRow, error) {
	rows, err := q.db.Query(ctx, listPenjualan,
		arg.Tanggal,
		arg.Tanggal_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPenjualanRow
	for rows.Next() {
		var i ListPenjualanRow
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDPelanggan,
			&i.Total,
			&i.Tanggal,
			&i.MetodePembayaran,
			&i.StatusPembayaran,
			&i.IDTransaksiGateway,
			&i.NamaPelanggan,
			&i.Kasir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
