// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) AS count
FROM products
WHERE is_active = true
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price, stock, image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

type CreateProductParams struct {
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products
WHERE id = $1
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
  id,
  name,
  price,
  stock,
  image_url,
  is_active
FROM products
ORDER BY created_at $3
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Column3 interface{} `json:"column_3"`
}

type ListProductsRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
  name = $2,
  price = $3,
  stock = $4,
  image_url = $5,
  is_active = $6,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

type UpdateProductParams struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
