// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price, stock, image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

type CreateProductParams struct {
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products
WHERE id = $1
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductAsc = `-- name: ListProductAsc :many
SELECT
  id,
  name,
  price,
  stock,
  image_url,
  is_active
FROM products
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListProductAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductAscRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) ListProductAsc(ctx context.Context, arg ListProductAscParams) ([]ListProductAscRow, error) {
	rows, err := q.db.Query(ctx, listProductAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductAscRow
	for rows.Next() {
		var i ListProductAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductDesc = `-- name: ListProductDesc :many
SELECT
  id,
  name,
  price,
  stock,
  image_url,
  is_active
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductDescParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductDescRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) ListProductDesc(ctx context.Context, arg ListProductDescParams) ([]ListProductDescRow, error) {
	rows, err := q.db.Query(ctx, listProductDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductDescRow
	for rows.Next() {
		var i ListProductDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
  name = $2,
  price = $3,
  stock = $4,
  image_url = $5,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

type UpdateProductParams struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
