// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) AS count
FROM products
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountProducts(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price, stock, image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

type CreateProductParams struct {
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products
WHERE id = $1
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT
  id,
  name,
  price,
  stock,
  image_url,
  is_active
FROM products
WHERE id = $1
`

type GetProductRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.IsActive,
	)
	return i, err
}

const listProductsAsc = `-- name: ListProductsAsc :many
SELECT
  id,
  name,
  price,
  stock,
  image_url,
  is_active
FROM products
WHERE name ILIKE '%' || $4 || '%'
ORDER BY $3 ASC
LIMIT $1 OFFSET $2
`

type ListProductsAscParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Column3 interface{} `json:"column_3"`
	Column4 pgtype.Text `json:"column_4"`
}

type ListProductsAscRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) ListProductsAsc(ctx context.Context, arg ListProductsAscParams) ([]ListProductsAscRow, error) {
	rows, err := q.db.Query(ctx, listProductsAsc,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsAscRow
	for rows.Next() {
		var i ListProductsAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsDesc = `-- name: ListProductsDesc :many
SELECT
  id,
  name,
  price,
  stock,
  image_url,
  is_active
FROM products
WHERE name ILIKE '%' || $4 || '%'
ORDER BY $3 DESC
LIMIT $1 OFFSET $2
`

type ListProductsDescParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Column3 interface{} `json:"column_3"`
	Column4 pgtype.Text `json:"column_4"`
}

type ListProductsDescRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) ListProductsDesc(ctx context.Context, arg ListProductsDescParams) ([]ListProductsDescRow, error) {
	rows, err := q.db.Query(ctx, listProductsDesc,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsDescRow
	for rows.Next() {
		var i ListProductsDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
  name = $2,
  price = $3,
  stock = $4,
  image_url = $5,
  is_active = $6,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, price, stock, is_active, image_url, created_at, updated_at
`

type UpdateProductParams struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	ImageUrl string         `json:"image_url"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
