// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) AS count
FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  id_user,
  id_customer,
  total,
  payment_method,
  id_transaction_gateway
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, id_user, id_customer, date, total, payment_method, payment_status, id_transaction_gateway, created_at, updated_at
`

type CreateTransactionParams struct {
	IDUser               pgtype.UUID    `json:"id_user"`
	IDCustomer           pgtype.UUID    `json:"id_customer"`
	Total                pgtype.Numeric `json:"total"`
	PaymentMethod        PaymentMethod  `json:"payment_method"`
	IDTransactionGateway pgtype.Text    `json:"id_transaction_gateway"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.IDUser,
		arg.IDCustomer,
		arg.Total,
		arg.PaymentMethod,
		arg.IDTransactionGateway,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCustomer,
		&i.Date,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.IDTransactionGateway,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
  t.id,
  t.id_user,
  t.id_customer,
  t.total,
  t.date,
  t.payment_method,
  t.payment_status,
  t.id_transaction_gateway,
  c.name AS customer_name,
  u.username AS cashier
FROM transactions t
LEFT JOIN customers c ON t.id_customer = c.id
JOIN users u ON t.id_user = u.id
WHERE date BETWEEN $1 AND $2
ORDER BY t.date DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsParams struct {
	Date   pgtype.Timestamptz `json:"date"`
	Date_2 pgtype.Timestamptz `json:"date_2"`
	Limit  int32              `json:"limit"`
	Offset int32              `json:"offset"`
}

type ListTransactionsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	IDUser               pgtype.UUID        `json:"id_user"`
	IDCustomer           pgtype.UUID        `json:"id_customer"`
	Total                pgtype.Numeric     `json:"total"`
	Date                 pgtype.Timestamptz `json:"date"`
	PaymentMethod        PaymentMethod      `json:"payment_method"`
	PaymentStatus        PaymentStatus      `json:"payment_status"`
	IDTransactionGateway pgtype.Text        `json:"id_transaction_gateway"`
	CustomerName         pgtype.Text        `json:"customer_name"`
	Cashier              string             `json:"cashier"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDCustomer,
			&i.Total,
			&i.Date,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.IDTransactionGateway,
			&i.CustomerName,
			&i.Cashier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions SET
  payment_status = $2,
  payment_method = $3,
  id_transaction_gateway = $4,
  updated_at = NOW()
WHERE id = $1
RETURNING id, id_user, id_customer, date, total, payment_method, payment_status, id_transaction_gateway, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID                   pgtype.UUID   `json:"id"`
	PaymentStatus        PaymentStatus `json:"payment_status"`
	PaymentMethod        PaymentMethod `json:"payment_method"`
	IDTransactionGateway pgtype.Text   `json:"id_transaction_gateway"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus,
		arg.ID,
		arg.PaymentStatus,
		arg.PaymentMethod,
		arg.IDTransactionGateway,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCustomer,
		&i.Date,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.IDTransactionGateway,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
