// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) AS count
FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  id_user,
  id_customer,
  total,
  payment_method,
  id_transaction_gateway,
  date
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, id_user, id_customer, date, total, payment_method, payment_status, id_transaction_gateway, created_at, updated_at
`

type CreateTransactionParams struct {
	IDUser               pgtype.UUID    `json:"id_user"`
	IDCustomer           pgtype.UUID    `json:"id_customer"`
	Total                pgtype.Numeric `json:"total"`
	PaymentMethod        PaymentMethod  `json:"payment_method"`
	IDTransactionGateway pgtype.Text    `json:"id_transaction_gateway"`
	Date                 pgtype.Date    `json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.IDUser,
		arg.IDCustomer,
		arg.Total,
		arg.PaymentMethod,
		arg.IDTransactionGateway,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCustomer,
		&i.Date,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.IDTransactionGateway,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSalesPerDay = `-- name: ListSalesPerDay :many
SELECT
  TO_CHAR(date_trunc('day', date), 'YYYY-MM-DD') AS name,
  SUM(total) AS sales
FROM transactions
WHERE date >= $1 AND date <= $2
GROUP BY date_trunc('day', date)
ORDER BY name
`

type ListSalesPerDayParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type ListSalesPerDayRow struct {
	Name  string `json:"name"`
	Sales int64  `json:"sales"`
}

func (q *Queries) ListSalesPerDay(ctx context.Context, arg ListSalesPerDayParams) ([]ListSalesPerDayRow, error) {
	rows, err := q.db.Query(ctx, listSalesPerDay, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesPerDayRow
	for rows.Next() {
		var i ListSalesPerDayRow
		if err := rows.Scan(&i.Name, &i.Sales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesPerMonth = `-- name: ListSalesPerMonth :many
SELECT
  TO_CHAR(date_trunc('month', date), 'YYYY-MM') AS name,
  SUM(total) AS sales
FROM transactions
WHERE date >= $1 AND date <= $2
GROUP BY date_trunc('month', date)
ORDER BY name
`

type ListSalesPerMonthParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type ListSalesPerMonthRow struct {
	Name  string `json:"name"`
	Sales int64  `json:"sales"`
}

func (q *Queries) ListSalesPerMonth(ctx context.Context, arg ListSalesPerMonthParams) ([]ListSalesPerMonthRow, error) {
	rows, err := q.db.Query(ctx, listSalesPerMonth, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesPerMonthRow
	for rows.Next() {
		var i ListSalesPerMonthRow
		if err := rows.Scan(&i.Name, &i.Sales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesPerWeek = `-- name: ListSalesPerWeek :many
SELECT
  TO_CHAR(date_trunc('week', date), 'YYYY-MM-DD') AS name,
  SUM(total) AS sales
FROM transactions
WHERE date >= $1 AND date <= $2
GROUP BY date_trunc('week', date)
ORDER BY name
`

type ListSalesPerWeekParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type ListSalesPerWeekRow struct {
	Name  string `json:"name"`
	Sales int64  `json:"sales"`
}

func (q *Queries) ListSalesPerWeek(ctx context.Context, arg ListSalesPerWeekParams) ([]ListSalesPerWeekRow, error) {
	rows, err := q.db.Query(ctx, listSalesPerWeek, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesPerWeekRow
	for rows.Next() {
		var i ListSalesPerWeekRow
		if err := rows.Scan(&i.Name, &i.Sales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesPerYear = `-- name: ListSalesPerYear :many
SELECT
  TO_CHAR(date, 'YYYY') AS name,
  SUM(total) AS sales
FROM transactions
WHERE date >= $1 AND date <= $2
GROUP BY TO_CHAR(date, 'YYYY')
ORDER BY name
`

type ListSalesPerYearParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type ListSalesPerYearRow struct {
	Name  string `json:"name"`
	Sales int64  `json:"sales"`
}

func (q *Queries) ListSalesPerYear(ctx context.Context, arg ListSalesPerYearParams) ([]ListSalesPerYearRow, error) {
	rows, err := q.db.Query(ctx, listSalesPerYear, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesPerYearRow
	for rows.Next() {
		var i ListSalesPerYearRow
		if err := rows.Scan(&i.Name, &i.Sales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
  t.id,
  t.id_user,
  t.id_customer,
  t.total,
  t.date,
  t.payment_method,
  t.payment_status,
  t.id_transaction_gateway,
  c.name AS customer_name,
  u.username AS cashier
FROM transactions t
LEFT JOIN customers c ON t.id_customer = c.id
JOIN users u ON t.id_user = u.id
WHERE date BETWEEN $1 AND $2
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListTransactionsRow struct {
	ID                   pgtype.UUID    `json:"id"`
	IDUser               pgtype.UUID    `json:"id_user"`
	IDCustomer           pgtype.UUID    `json:"id_customer"`
	Total                pgtype.Numeric `json:"total"`
	Date                 pgtype.Date    `json:"date"`
	PaymentMethod        PaymentMethod  `json:"payment_method"`
	PaymentStatus        PaymentStatus  `json:"payment_status"`
	IDTransactionGateway pgtype.Text    `json:"id_transaction_gateway"`
	CustomerName         pgtype.Text    `json:"customer_name"`
	Cashier              string         `json:"cashier"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDCustomer,
			&i.Total,
			&i.Date,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.IDTransactionGateway,
			&i.CustomerName,
			&i.Cashier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatusByPaymentId = `-- name: UpdateStatusByPaymentId :one
UPDATE transactions SET
  payment_status = $2,
  updated_at = NOW()
WHERE id_transaction_gateway = $1
RETURNING id, id_user, id_customer, date, total, payment_method, payment_status, id_transaction_gateway, created_at, updated_at
`

type UpdateStatusByPaymentIdParams struct {
	IDTransactionGateway pgtype.Text   `json:"id_transaction_gateway"`
	PaymentStatus        PaymentStatus `json:"payment_status"`
}

func (q *Queries) UpdateStatusByPaymentId(ctx context.Context, arg UpdateStatusByPaymentIdParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateStatusByPaymentId, arg.IDTransactionGateway, arg.PaymentStatus)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCustomer,
		&i.Date,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.IDTransactionGateway,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions SET
  payment_status = $2,
  payment_method = $3,
  id_transaction_gateway = $4,
  total = $5,
  updated_at = NOW()
WHERE id = $1
RETURNING id, id_user, id_customer, date, total, payment_method, payment_status, id_transaction_gateway, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID                   pgtype.UUID    `json:"id"`
	PaymentStatus        PaymentStatus  `json:"payment_status"`
	PaymentMethod        PaymentMethod  `json:"payment_method"`
	IDTransactionGateway pgtype.Text    `json:"id_transaction_gateway"`
	Total                pgtype.Numeric `json:"total"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus,
		arg.ID,
		arg.PaymentStatus,
		arg.PaymentMethod,
		arg.IDTransactionGateway,
		arg.Total,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCustomer,
		&i.Date,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.IDTransactionGateway,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
