paths:
  /products:
    post:
      summary: Create a new product
      description: Add a new product with name, price, and stock
      tags:
        - products
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CreateProductInput"
      responses:
        "201":
          description: Successfully added product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSingleResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      summary: List products
      description: Get a paginated list of products with optional ordering and search
      tags:
        - products
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Current page
        - in: query
          name: per_page
          schema:
            type: integer
          description: Items per page
        - in: query
          name: order_by
          schema:
            type: string
          description: Order by field
        - in: query
          name: order_dir
          schema:
            type: string
            enum:
              - asc
              - desc
          description: Order direction
        - in: query
          name: search
          schema:
            type: string
          description: Search query
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductListResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /products/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Product ID
    get:
      summary: Get product details
      description: Get a single product by ID
      tags:
        - products
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Product details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSingleResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      summary: Update a product
      description: Update product name, price, stock, image_url, and is_active
      tags:
        - products
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UpdateProductInput"
      responses:
        "200":
          description: Successfully updated product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSingleResponse"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      summary: Delete a product
      description: Delete a product by ID
      tags:
        - products
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully deleted product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSingleResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /products/count:
    get:
      summary: Get total products
      description: Get the total count of products
      tags:
        - products
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Total products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductCountResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Pagination:
      type: object
      properties:
        current_page:
          type: integer
          example: 1
        per_page:
          type: integer
          example: 10
        total_pages:
          type: integer
          nullable: true
          example: 5

    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 11111111-1111-1111-1111-111111111111
        name:
          type: string
          example: Coffee
        price:
          type: string
          description: Integer string representation
          example: "15000"
        stock:
          type: integer
          example: 100
        is_active:
          type: boolean
          example: true
        image_url:
          type: string
          example: https://cdn.example.com/images/product.png
        created_at:
          type: string
          format: date-time
          example: 2025-01-01T12:00:00Z
        updated_at:
          type: string
          format: date-time
          example: 2025-01-02T12:00:00Z

    CreateProductInput:
      type: object
      required:
        - name
        - price
        - stock
      properties:
        name:
          type: string
          description: Min 2 characters
          example: Coffee
        price:
          type: string
          description: Integer string greater than zero
          example: "15000"
        stock:
          type: integer
          description: Non-negative integer
          example: 100
        image_url:
          type: string
          description: Optional
          example: https://cdn.example.com/images/product.png

    UpdateProductInput:
      type: object
      required:
        - name
        - price
        - stock
        - image_url
        - is_active
      properties:
        name:
          type: string
          example: Coffee Latte
        price:
          type: string
          description: Integer string
          example: "18000"
        stock:
          type: integer
          example: 80
        image_url:
          type: string
          example: https://cdn.example.com/images/product-latte.png
        is_active:
          type: boolean
          example: true

    ProductSingleResponse:
      type: object
      description: Standard success envelope returning a single Product
      properties:
        success:
          type: boolean
          example: true
        status_code:
          type: integer
          example: 200
        message:
          type: string
          example: Successfully added product
        data:
          $ref: "#/components/schemas/Product"

    ProductListResponse:
      type: object
      description: Success envelope returning a list of Products with pagination
      properties:
        success:
          type: boolean
          example: true
        status_code:
          type: integer
          example: 200
        message:
          type: string
          example: List of products
        data:
          type: array
          items:
            $ref: "#/components/schemas/Product"
        pagination:
          $ref: "#/components/schemas/Pagination"

    ProductCountResponse:
      type: object
      description: Success envelope returning a products total count
      properties:
        success:
          type: boolean
          example: true
        status_code:
          type: integer
          example: 200
        message:
          type: string
          example: Total products
        data:
          type: integer
          example: 42

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        status_code:
          type: integer
          example: 400
        message:
          type: string
          example: Validation error
        data:
          nullable: true
